# -*- coding: utf-8 -*-
"""EDI_SEM6_knife-dection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cXqGAgGgHpBLiXNnMPgNSmRj7RFxEzaz
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Check For Grafics Card"""

!nvidia-smi

"""# Installations"""

!pip install ultralytics

from ultralytics import YOLO

"""# Testing Installations"""

!yolo task=detect mode=predict model=yolov8l.pt conf=0.25 source="https://ultralytics.com/images/bus.jpg"

"""# **CUSTOM TRAINING**"""

!yolo task=detect mode=train model=yolov8l.pt data=../content/drive/MyDrive/Datasets/knifeDataset/data.yaml epochs=50 imgsz=640